name: Build

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Build And Run Tests
        run: |
          npm ci
          npm run build
